### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by zulln** [Tomasuh/Tomasuh.github.io#1]
You set the site url to http://tomasuh.github.io in your config but the blog could be available over https as the blog is hosted at *.github.io.

You should somehow disable https(if that's even possible in a nice way?) or better make it work over https.

**Comment by zulln** [comment]
I guess the proper solution would be to set site.url to "//tomasuh.github.io". Just make sure that doesn't break anything else first.

**Comment by Tomasuh** [comment]
Thanks, the second comment was a working solution.
